language: node_js
node_js:
  - "9"
  - "8"
  - "lts/*"
script:
  - yarn run lint
  - yarn run test
  - yarn run build
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
install:
  - CC=gcc-4.9 CXX=g++-4.9 npm install
